server:
  port: ${PORT:8080}

spring:
  application:
    name: bancodigital
  datasource:
    driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format-sql: true
